### ISSUE TITLE
How to predict enhanced dependencies?

### ISSUE THREAD

**Issue by yashkens** [Alibaba-NLP/MultilangStructureKD#9]
Hello!
I trained model on Russian data with help of your config file. But I can't use it to predict dependencies. 
I tried using command below, but it started to train the model again.
```python3 train_with_teacher.py --config config/xlmr_1000epoch_0.1inter_2000batch_0.002lr_400hidden_ru_monolingual_nocrf_fast_2nd_nodev_enhancedud15.yaml --predict```
I also tried importing model in python and doing ```model([sentence])```, where sentence is an instance of Sentence class, but it gave this error: ```AttributeError: 'list' object has no attribute 'features'```
I also tried passing my data to ```model(data)``` as UniversalDependenciesDataset object, but it didn't help:
 ``` File "<stdin>", line 1, in <module>
  File "/home/my_folder/.conda/envs/alibaba-nlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541_call__
    result = self.forward(*input, **kwargs)
  File "/home/my_folder/MultilangStructureKD/flair/models/dependency_model.py", line 524, in forward
    sentence_tensor = torch.cat([sentences.features[x].to(flair.device) for x in sentences.features],-1)
AttributeError: 'UniversalDependenciesDataset' object has no attribute 'features' 
```
Can you give me any hints on how to use it? Thank you in advance!

**Comment by wangxinyu0922** [comment]
Hi, if you want to parse a certain unlabeled file, please run this command (taking iwpt 2020 ru test set as an example):
```
python train_with_teacher.py --config config/xlmr_1000epoch_0.1inter_2000batch_0.002lr_400hidden_ru_monolingual_nocrf_fast_2nd_nodev_enhancedud15.yaml --parse --target_dir iwpt2020_test/ru --keep_order --batch_size 1000
```

If you just want to parse the test set (containing the gold label), run:
```
python train_with_teacher.py --config config/xlmr_1000epoch_0.1inter_2000batch_0.002lr_400hidden_ru_monolingual_nocrf_fast_2nd_nodev_enhancedud15.yaml --test --keep_order --batch_size 1000
```

The argument `predict` might be confusing to you. It is not for prediction.

**Comment by yashkens** [comment]
Thank you so much! It works now.
